image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
    
  - apt-get update
  - apt-get install -y wget unzip curl gnupg

  - curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

  - apt-get update
  - apt-get install -y google-chrome-stable

  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - pip install behave
  - pip install selenium
  - pip install webdriver-manager
  - virtualenv venv
  - source venv/bin/activate


tests:
  script:
    - behave
  artifacts:
    paths:
      - build/*


