image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - pip install behave
  - pip install selenium
  - pip install webdriver-manager
  - virtualenv venv
  - source venv/bin/activate


tests:
  script:
    - pytest tests.py
  artifacts:
    paths:
      - build/*


